# -*- coding: utf-8 -*-
"""Major project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sj0l-Nj8LjjruqvJTOUkM9hZhX5wTL_H
"""

!nvidia-smi

!pip install ultralytics

from ultralytics import YOLO
import os
from IPython.display import display

# Instantiate YOLO object
yolo = YOLO()

!pip install roboflow

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="vwTq8JiF4cmibZGpzfGh")
project = rf.workspace("huiyao-hu-sj18e").project("construction-ppe-detection")
version = project.version(1)
dataset = version.download("yolov8")

from google.colab import drive
drive.mount('/content/drive')

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640 project = '/content/drive/MyDrive/major project'

!cp -r '/content/Construction-PPE-Detection-1' '/content/drive/MyDrive/major project'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/video.mp4'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/Construction Worker Stock Footage COPYRIGHT FREE (1).mp4'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/Workers at the Construction Site Stock Video.mp4'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.55 source= '/content/drive/MyDrive/major project/Screenshot 2024-03-15 180806.png'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/Royalty Free 4K Stock Footage _ Free Download _ Construction Workers On Site.mp4'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/Screenshot 2024-03-15 182003.png'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/ss.png'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/Screenshot 2024-03-15 182449.png'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/istockphoto-609880480-640_adpp_is.mp4'

!yolo task=detect mode=predict model= '/content/drive/MyDrive/major project/train2/weights/best.pt' conf=0.77 source= '/content/drive/MyDrive/major project/11.mp4'

!cp -r '/content/runs' '/content/drive/MyDrive/major project'